// USER
export const USER_LOGIN = "SET_LOGED_IN";
export const USER_LOGOUT = "SET_LOGED_IN";

// STORE
export const GET_STORES= "GET_STORES";
export const ADD_STORE = "ADD_STORE";
export const REMOVE_STORE="REMOVE_STORE";
export const EDIT_STORE = "EDIT_STORE";

//SERVICE
export const GET_SERVICES="GET_SERVICES";
export const ADD_SERVICE="ADD_SERVICE";
export const REMOVE_SERVICE="REMOVE_SERVICE";
export const EDIT_SERVICE="EDIT_SERVICE";

//NOTIFICATIONS
export const GET_NOTIFICATIONS="GET_NOTIFICATIONS"
export const MARK_READ="MARK_READ"
export const REMOVE_NOTIFICATION="REMOVE_NOTIFICATIONS"

//SERVICE HISTORY
export const GET_HISTORY ="GET_HISTORY"
export const CREATE_HISTORY="CREATE_HISTORY"
export const REMOVE_HISTORY="REMOVE_HISTORY"
